version: "3.8"
services:
  backend-app:
    build: ./backend-app
    image: backend_app
    ports: 
      - 8080:8080
      - 1337:1337
    extra_hosts:
      - "host.docker.internal:host-gateway"

    volumes:
      - ./backend-app/src:/backend-app/src
    env_file: ./backend-app/.env
    depends_on: 
      - postgre_db
  postgre_db:
    build: ./postgres-db
    image: postgre_db
    container_name: postgre_db
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_DB: postgredb
      POSTGRES_PASSWORD: abc123