name: Backend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  Start-Backend-App:

    runs-on: ubuntu-latest
    #Environment used to access secrets
    environment: ENVIRONMENT_NAME_GOES_HERE
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout Branch
      uses: actions/checkout@v3
    
    # Creates a .env file with the variables succeeding envkey_
    # i.e: envkey_PORT: 8080
    # creates: PORT=8080
    # in the directory backend-app/
    - name: Create .env file
      
      uses: SpicyPizza/create-envfile@v1.3.0
      with:
        envkey_PORT: 8080
        envkey_RUN_OCPP_TEST: 0
        envkey_USE_LOCAL_DATABASE: 1
        
        directory: backend-app/
        
        # When secrets exist use these calls to obfuscate
        #envkey_AWS_REGION: ${{ secrets.AWS_REGION }}
        #envkey_USER_POOL: ${{ secrets.USER_POOL }}
        #envkey_USER_POOL_ID: ${{ secrets.USER_POOL_ID }}
        #envkey_USER_POOL_SECRET: ${{ secrets.USER_POOL_SECRET }}
        #envkey_ADMIN_POOL: ${{ secrets.ADMIN_POOL }}
        #envkey_ADMIN_POOL_ID: ${{ secrets.ADMIN_POOL_ID }}
        #envkey_ADMIN_POOL_SECRET: ${{ secrets.ADMIN_POOL_SECRET }}
        
        # TEMPORARY SOLUTION, DELETE WHEN SECRETS ARE IMPLEMENTED
        envkey_AWS_REGION: eu-west-1
        envkey_USER_POOL: eu-west-1_NqeTT8tjs
        envkey_USER_POOL_ID: 1h94cs3udp5tbqkdbeblm3ttke
        envkey_USER_POOL_SECRET: 1gaae856sc7h8u6r1m3lp6tb70uk2gkd8n0qgsaumebc10mk38q3
        envkey_ADMIN_POOL: eu-west-1_tPq5id1uh
        envkey_ADMIN_POOL_ID: mq90k6fets8944tapp6tjgme8
        envkey_ADMIN_POOL_SECRET: 1nqmrsp2rmf6dfplcu5v9sfho8sque1pn2a33b9vr147bkobpr2v

    # Run the backend app
    # & is used to signal that this task will keep running, as to not get stuck on this step
    - name: launch docker container
      run: docker-compose up &
      
  Run-Backend-Tests:
    # Runs sequentially to starting the back-end app
    needs: Start-Backend-App
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
    
    - name: Execute tests
    
    # Runs a set of commands using the runners shell
      run: |
        export PYTHONPATH=.
        pip install -r ./test/requirements.txt
      
    - name: Run PyTest
      run: |
        python -m pytest ./test/backend_tests --junit-xml=report.xml
      
    - name: Publish test result
      uses: mikepenz/action-junit-report@v3
      if: always() # always run even if the previous step fails
      with:
        report_paths: '**/*.xml'
        
